.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 2008-05-05               \" DATE 
.Dt eyed 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm eyed,
.Nd This line parsed for whatis database.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
path ...                 \" Arguments
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Bl -tag -width -indent  \" Begins a tagged list 
.It path               \" Each item preceded by .It macro
Path to a Mercurial repository to be monitored and managed.
.El                      \" Ends the list
.Pp
