.Dd 2008-05-07               \" DATE 
.Dt eyed 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm eyed,
.Nd This line parsed for whatis database.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
path ...                 \" Arguments
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Bl -tag -width -indent  \" Begins a tagged list 
.It path               \" Each item preceded by .It macro
Path to a Mercurial repository to be monitored and managed.
.El                      \" Ends the list
.Pp
